service: ssm-agent-mon
custom:
  stage_config: ${file(config-${opt:stage}.yml)}
provider:
  name: aws
  runtime: ruby2.7
  memorySize: 128
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
        - cloudwatch:ListMetrics
        - ssm:SendCommand
        - ssm:DescribeInstanceInformation
      Resource:
        - "*"

functions:
  SsmAgentMon:
    handler: lambda/ssm-run-doc.lambda_handler
    events:
      - schedule: rate(1 minute)
resources:
  Resources:
    ImageQueueDepthAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: Alarm triggers when SSM agents are not registering
        Namespace: mi-health
        MetricName: heart-beat
        Dimensions:
          - Name: InstanceID
            Value: mi-06ddebecd7e7cf8e1
        Statistic: Maximum
        Period: 60
        EvaluationPeriods: 5
        Threshold: 1
        ComparisonOperator: LessThanThreshold
        AlarmActions:
          - ${self:custom.stage_config.alarm_sns_arn}
        OKActions:
          - ${self:custom.stage_config.alarm_sns_arn}
